# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MTMusicDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MTMusicDemo
	pod ‘DOUAudioStreamer’, ‘0.2.15’
	pod 'SDWebImage'
  target 'MTMusicDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MTMusicDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
